name       : mlt
version    : 6.16.0
release    : 17
source     :
    - https://github.com/mltframework/mlt/releases/download/v6.16.0/mlt-6.16.0.tar.gz : d9fcc2d43f0f76805f53adca70e9795bfea7952805d77d14be3a2a363fb1edc3
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
rundeps    :
    - frei0r
setup      : |
    %configure --enable-gpl --enable-gpl3 --enable-opengl
build      : |
    %make
install    : |
    %make_install
