name       : mlt
version    : 6.4.1
release    : 6
source     :
    - https://github.com/mltframework/mlt/archive/v6.4.1.tar.gz : 87583af552695b2235f4ee3fc1e645d69e31702b109331d7e8785fb180cfa382
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL_image)
rundeps    :
    - frei0r
setup      : |
    %configure --enable-gpl --enable-gpl3
build      : |
    %make
install    : |
    %make_install
