name       : mlt
version    : 6.14.0
release    : 16
source     :
    - https://github.com/mltframework/mlt/archive/v6.14.0.tar.gz : d387350f7bb7dd01efce3933c5ab7987b596e98bef7cc9c2349524d55a808b5e
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
rundeps    :
    - frei0r
setup      : |
    %configure --enable-gpl --enable-gpl3 --enable-opengl
build      : |
    %make
install    : |
    %make_install
