name       : mlt
version    : 6.22.1
release    : 24
source     :
    - https://github.com/mltframework/mlt/archive/v6.22.1.tar.gz : a3debdf0b8811f0d20c902cc3df3d05dad7d3ff36d1db16c0a7338d0d5989998
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
    - pkgconfig(x11)
rundeps    :
    - frei0r
setup      : |
    %patch -p1 < $pkgfiles/0002-Fix-make-install-for-lumas.patch
    %configure --enable-gpl --enable-gpl3 --enable-opengl --enable-lumas
build      : |
    %make
install    : |
    %make_install
