name       : mlt
version    : 6.10.0
release    : 12
source     :
    - https://github.com/mltframework/mlt/releases/download/v6.10.0/mlt-6.10.0.tar.gz : 10642a80f81e12c6cc5405e60ced640b3dd325c793fe73207ae07de321ad6810
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
rundeps    :
    - frei0r
setup      : |
    %configure --enable-gpl --enable-gpl3 --enable-opengl
build      : |
    %make
install    : |
    %make_install
