name       : mlt
version    : 7.2.0
release    : 34
source     :
    - https://github.com/mltframework/mlt/archive/refs/tags/v7.2.0.tar.gz : 34b737fae61dabddf3ec64477298decb9b2076388ccbda7e50114996b268086d
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
patterns   :
    - python :
        - /usr/lib/python3.*/site-packages/*
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(python3)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
    - pkgconfig(x11)
    - swig
rundeps    :
    - frei0r
setup      : |
    %cmake_ninja \
        -DMOD_GDK=OFF \
        -DSWIG_PYTHON=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
