name       : mlt
version    : 6.6.0
release    : 10
source     :
    - https://github.com/mltframework/mlt/releases/download/v6.6.0/mlt-6.6.0.tar.gz : 28cbc5974f72ef228d624a58809c7c8055372f5f62f5882dc055099d444b2cdd
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
rundeps    :
    - frei0r
setup      : |
    %configure --enable-gpl --enable-gpl3 --enable-opengl
build      : |
    %make
install    : |
    %make_install
