name       : mlt
version    : 6.2.0
release    : 1
source     :
    - https://github.com/mltframework/mlt/archive/v6.2.0.tar.gz : dd2ee742e89620de78a259790f92a7cadad67f0e0a6c1ea7ed932f96fb739fff
license    :
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.1
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(Qt5Core)
    - pkgconfig(samplerate)
    - pkgconfig(SDL_image)
setup      : |
    %configure --enable-gpl --enable-gpl3
build      : |
    %make
install    : |
    %make_install
