name       : mlt
version    : 6.20.0
release    : 21
source     :
    - https://github.com/mltframework/mlt/releases/download/v6.20.0/mlt-6.20.0.tar.gz : ab211e27c06c0688f9cbe2d74dc0623624ef75ea4f94eea915cdc313196be2dd
license    :
    - GPL-2.0-or-later
    - GPL-3.0-or-later
    - LGPL-2.1-or-later
component  : multimedia.library
summary    : Multimedia framework designed for television broadcasting.
description: |
    Multimedia framework designed for television broadcasting.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(frei0r)
    - pkgconfig(gl)
    - pkgconfig(libavformat)
    - pkgconfig(libexif)
    - pkgconfig(libpulse)
    - pkgconfig(movit)
    - pkgconfig(Qt5Svg)
    - pkgconfig(samplerate)
    - pkgconfig(SDL2_image)
    - pkgconfig(vidstab)
rundeps    :
    - frei0r
setup      : |
    %patch -p1 < $pkgfiles/0001-mlt-opencv4.patch
    %patch -p1 < $pkgfiles/0002-Fix-make-install-for-lumas.patch
    %configure --enable-gpl --enable-gpl3 --enable-opengl --enable-lumas
build      : |
    %make
install    : |
    %make_install
